# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/geraldmas/MAS_gpu_project_corrigé

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/geraldmas/MAS_gpu_project_corrigé

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/geraldmas/MAS_gpu_project_corrigé/CMakeFiles /Users/geraldmas/MAS_gpu_project_corrigé/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/geraldmas/MAS_gpu_project_corrigé/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BS_Monte_Carlo

# Build rule for target.
BS_Monte_Carlo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BS_Monte_Carlo
.PHONY : BS_Monte_Carlo

# fast build rule for target.
BS_Monte_Carlo/fast:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/build
.PHONY : BS_Monte_Carlo/fast

src/FinancialAsset.o: src/FinancialAsset.cpp.o

.PHONY : src/FinancialAsset.o

# target to build an object file
src/FinancialAsset.cpp.o:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/FinancialAsset.cpp.o
.PHONY : src/FinancialAsset.cpp.o

src/FinancialAsset.i: src/FinancialAsset.cpp.i

.PHONY : src/FinancialAsset.i

# target to preprocess a source file
src/FinancialAsset.cpp.i:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/FinancialAsset.cpp.i
.PHONY : src/FinancialAsset.cpp.i

src/FinancialAsset.s: src/FinancialAsset.cpp.s

.PHONY : src/FinancialAsset.s

# target to generate assembly for a file
src/FinancialAsset.cpp.s:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/FinancialAsset.cpp.s
.PHONY : src/FinancialAsset.cpp.s

src/auxiliary.o: src/auxiliary.cpp.o

.PHONY : src/auxiliary.o

# target to build an object file
src/auxiliary.cpp.o:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/auxiliary.cpp.o
.PHONY : src/auxiliary.cpp.o

src/auxiliary.i: src/auxiliary.cpp.i

.PHONY : src/auxiliary.i

# target to preprocess a source file
src/auxiliary.cpp.i:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/auxiliary.cpp.i
.PHONY : src/auxiliary.cpp.i

src/auxiliary.s: src/auxiliary.cpp.s

.PHONY : src/auxiliary.s

# target to generate assembly for a file
src/auxiliary.cpp.s:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/auxiliary.cpp.s
.PHONY : src/auxiliary.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BS_Monte_Carlo.dir/build.make CMakeFiles/BS_Monte_Carlo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BS_Monte_Carlo"
	@echo "... src/FinancialAsset.o"
	@echo "... src/FinancialAsset.i"
	@echo "... src/FinancialAsset.s"
	@echo "... src/auxiliary.o"
	@echo "... src/auxiliary.i"
	@echo "... src/auxiliary.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

